version: '3'

services:
    rev1:
        image: rev1
        container_name: rev1
        build:
          context: ./source/
        ports:
          - '20001:5000'
        restart: always

networks:
  default:
    external:
      name: ctf-network
