version: '3'

services:
    pwn2:
        image: pwn2
        container_name: pwn2
        build:
          context: ./source/
        ports:
          - '10002:5000'
        restart: always

networks:
  default:
    external:
      name: ctf-network
